version: 1.0.{build}
image: Visual Studio 2017
configuration: Release

before_build:
  - cmd: >-
      cd src

      dotnet restore

build:
  verbosity: minimal

test_script:
  - cmd: dotnet test src/Turbocharged.NSQ.Tests/Turbocharged.NSQ.Tests.csproj

artifacts:
  - path: '*.nupkg'
