version: 1.0.{build}
image: Visual Studio 2017
configuration: Release

before_build:
  - cmd: dotnet restore

build:
  verbosity: minimal

test_script:
  - cmd: dotnet test src/Turbocharged.NSQ.Tests/Turbocharged.NSQ.Tests.csproj

after_build:
  - cmd: dotnet pack -c $(configuration) src/Turbocharged.NSQ/Turbocharged.NSQ.csproj

artifacts:
  - path: '**/*.nupkg'
